### Register
POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json

{
  "email": "ramil@yabbarov.ru",
  "password": "password"
}


### Register user
POST http://localhost:8080/api/v1/auth/register
Content-Type: application/json

{
  "email": "user@yabbarov.ru",
  "password": "password"
}


### Login
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "email": "ramil@yabbarov.ru",
  "password": "password"
}


### Logout
POST http://localhost:8080/api/v1/auth/logout

### Me
GET http://localhost:8080/api/v1/auth/me


### Get PersonTableRow with id == 1
GET http://localhost:8080/api/v1/person/1
Content-Type: application/json


### PersonTablePage
GET http://localhost:8080/api/v1/person/all
Content-Type: application/json
